nodeLinker: node-modules
enableGlobalCache: true

packageExtensions:
  "@dynamic-labs/sdk-react-core@*":
    peerDependencies:
      "react": "^19.0.0"
      "react-dom": "^19.0.0"
  "@dynamic-labs/iconic@*":
    peerDependencies:
      "react": "^19.0.0"
      "react-dom": "^19.0.0" 