"""Initial migration

Revision ID: 2aad8496f68b
Revises: 
Create Date: 2024-12-07 23:07:40.724765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2aad8496f68b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telegram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('warpcast_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('character_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('warpcast_app_key', sa.Text(), nullable=True))
        batch_op.alter_column('creator',
               existing_type=sa.VARCHAR(length=42),
               nullable=True)
        batch_op.drop_column('telegram_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('verified_creator')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verified_creator', sa.VARCHAR(length=42), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telegram_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('creator',
               existing_type=sa.VARCHAR(length=42),
               nullable=False)
        batch_op.drop_column('warpcast_app_key')
        batch_op.drop_column('character_prompt')
        batch_op.drop_column('warpcast_url')
        batch_op.drop_column('description')
        batch_op.drop_column('telegram')
        batch_op.drop_column('twitter')
        batch_op.drop_column('name')
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
