"""character json in api

Revision ID: afc8d4cf2d25
Revises: 2aad8496f68b
Create Date: 2024-12-14 16:15:26.951999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc8d4cf2d25'
down_revision = '2aad8496f68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_character', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_column('ai_character')

    # ### end Alembic commands ###
