/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BondingCurveInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "A"
      | "B"
      | "getEthBuyQuote"
      | "getEthSellQuote"
      | "getTokenBuyQuote"
      | "getTokenSellQuote"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "A", values?: undefined): string;
  encodeFunctionData(functionFragment: "B", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getEthBuyQuote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEthSellQuote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenBuyQuote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenSellQuote",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "A", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "B", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEthBuyQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEthSellQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBuyQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenSellQuote",
    data: BytesLike
  ): Result;
}

export interface BondingCurve extends BaseContract {
  connect(runner?: ContractRunner | null): BondingCurve;
  waitForDeployment(): Promise<this>;

  interface: BondingCurveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  A: TypedContractMethod<[], [bigint], "view">;

  B: TypedContractMethod<[], [bigint], "view">;

  getEthBuyQuote: TypedContractMethod<
    [currentSupply: BigNumberish, ethOrderSize: BigNumberish],
    [bigint],
    "view"
  >;

  getEthSellQuote: TypedContractMethod<
    [currentSupply: BigNumberish, ethOrderSize: BigNumberish],
    [bigint],
    "view"
  >;

  getTokenBuyQuote: TypedContractMethod<
    [currentSupply: BigNumberish, tokenOrderSize: BigNumberish],
    [bigint],
    "view"
  >;

  getTokenSellQuote: TypedContractMethod<
    [currentSupply: BigNumberish, tokensToSell: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(nameOrSignature: "A"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "B"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEthBuyQuote"
  ): TypedContractMethod<
    [currentSupply: BigNumberish, ethOrderSize: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEthSellQuote"
  ): TypedContractMethod<
    [currentSupply: BigNumberish, ethOrderSize: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenBuyQuote"
  ): TypedContractMethod<
    [currentSupply: BigNumberish, tokenOrderSize: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenSellQuote"
  ): TypedContractMethod<
    [currentSupply: BigNumberish, tokensToSell: BigNumberish],
    [bigint],
    "view"
  >;

  filters: {};
}
