"""temp request token

Revision ID: 4aa6672b3219
Revises: ccb70347ab8b
Create Date: 2024-12-14 21:34:13.524321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa6672b3219'
down_revision = 'ccb70347ab8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('temp_request_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'temp_request_token')
    # ### end Alembic commands ###
