"""twitter flows

Revision ID: d5dddb6b9ead
Revises: afc8d4cf2d25
Create Date: 2024-12-14 18:12:55.556094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5dddb6b9ead'
down_revision = 'afc8d4cf2d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter_oauth_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_oauth_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_user_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_username', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_column('twitter_username')
        batch_op.drop_column('twitter_user_id')
        batch_op.drop_column('twitter_oauth_secret')
        batch_op.drop_column('twitter_oauth_token')

    # ### end Alembic commands ###
