"""Add tweets table

Revision ID: ccb70347ab8b
Revises: d5dddb6b9ead
Create Date: 2024-12-14 20:54:58.500074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb70347ab8b'
down_revision = 'd5dddb6b9ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
