/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { BondingCurve, BondingCurveInterface } from "../BondingCurve";

const _abi = [
  {
    type: "function",
    name: "A",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "B",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEthBuyQuote",
    inputs: [
      {
        name: "currentSupply",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "ethOrderSize",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getEthSellQuote",
    inputs: [
      {
        name: "currentSupply",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "ethOrderSize",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getTokenBuyQuote",
    inputs: [
      {
        name: "currentSupply",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "tokenOrderSize",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getTokenSellQuote",
    inputs: [
      {
        name: "currentSupply",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "tokensToSell",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "error",
    name: "InsufficientLiquidity",
    inputs: [],
  },
] as const;

export class BondingCurve__factory {
  static readonly abi = _abi;
  static createInterface(): BondingCurveInterface {
    return new Interface(_abi) as BondingCurveInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BondingCurve {
    return new Contract(address, _abi, runner) as unknown as BondingCurve;
  }
}
